### ISSUE TITLE
[C#] Releasing a scene does not release resources owned by that scene

### ISSUE THREAD

**Issue by mattbenic** [AtomicGameEngine/AtomicGameEngine#1471]
To reproduce

1) add the following destructor to 04_StaticScene.cs in the FeatureExamples project:
```
~StaticSceneSample()
{
    GetSubsystem<Player>().UnloadScene(scene);
    ResourceCache cache = AtomicNET.GetSubsystem<ResourceCache>();
    cache.ReleaseAllResources(false);
}
```
2) run the project with metrics enabled
3) run the _Static Scene_ sample
4) Exit the sample by pressing escape
5) Watch the metrics, after a few seconds theGC will run and Scene should disappear from the list of objects. Note that all other objects from the scene (geometry, Textures, etc) will remain

**Comment by JoshEngebretson** [comment]
@mattbenic Thanks for the report, I'll have a look into this later today, visual object metrics FTW! 👍

**Comment by JoshEngebretson** [comment]
Ok, #1473 should fix the bug side of this issue.  A tad on the ironic side, the metrics WeakPtr references were keeping the resources alive, as the ResourceCache holds resources with weak references, doh!

I switched to raw pointers on the object metrics as this should be fine (RefCounted instances are added immediately at creation and removed only at destruction).

Some notes:

```
GetSubsystem<Player>().UnloadScene(scene);
```
This has no effect in the FeatureExamples scene as it is new'd and doesn't load a Scene through the Player subsystem

```
ResourceCache cache = AtomicNET.GetSubsystem<ResourceCache>();
cache.ReleaseAllResources(false);
```
This is awkward in GC environments as references to models, etc, have to be GC'd before ```cache.ReleaseAllResources(true);``` will release the resources.  This can take a bit, even when aggressively calling ```System.GC.Collect();```

**Comment by mattbenic** [comment]
Thanks Josh. So what is the recommended pattern for fully unloading a scene
loaded with Player. LoadScene, and for a screen created with new, and
getting up their resources, as quickly as possible?

**Comment by mattbenic** [comment]
@JoshEngebretson With the latest code from master, I'm still seeing this behavior in our own scenes (loaded with Player.LoadScene) and those in the features example. I don't see any new commits on the examples repo, so I doubt it's something I've missed there. What was your test case to ensure this was fixed? Perhaps it will point me to what I'm doing wrong.

**Comment by JoshEngebretson** [comment]
@mattbenic The resources need to be released, once the stuff referring to them has been GC'd.  If there are any references to the resource, including weak references, ```cache.ReleaseAllResources(false);``` will not release the resource, and will continue to hold it.  I aggressively called ```System.GC.Collect();``` and also called ```cache.ReleaseAllResources(false);``` to confirm that the resources were released once the references were all GC'd.  

This is awkward as noted, and I will see what can be done in a new AtomicTest project, using the Player scene loading api.  This is a problem with GC in general and not limited to C#.

**Comment by mattbenic** [comment]
Ok. Another instance I saw of this, unrelated to scenes and maybe a good
simple first case to work with, was with File. I haven't had a chance to
build a simple test case yet, but we load a number of files, and then use
them via the steam wrapper I added. I've confirmed all C# references are
released (they're only used locally within a function, the steam passed
into a desexualized, and confirmed that the stream's inner reference is
cleared), and that the C# destructor is called, but they hang around
through multiple GCs (yay for VS told actually showing when GC happens!).

**Comment by mattbenic** [comment]
Ok. Another instance I saw of this, unrelated to scenes and maybe a good
simple first case to work with, was with File. I haven't had a chance to
build a simple test case yet, but we load a number of files, and then use
them via the stream wrapper I added. I've confirmed all C# references are
released (they're only used locally within a function, the steam passed
into a deserializer, and confirmed that the stream's inner reference is
cleared), and that the C# destructor is called, but they hang around
through multiple GCs (yay for VS told actually showing when GC happens!).

**Comment by JoshEngebretson** [comment]
I am not sure what the issue is there, is it that they aren't GC'd in C# when you would expect, or that the native instances are never released?

**Comment by mattbenic** [comment]
Sorry, that could have been much clearer :) The Atomic metrics still show them as alive, so I think that's misreporting.  I'm pretty sure they're getting closed on the native side because previously that wasn't happening, the stream wasn't releasing the file. That was easy to test for because the process would max out on open handles after multiple games. The managed object is getting gcd as well, breakpoints in the destructor are hit.

Multiple GCs here shouldn't matter, ignore that bit :)

**Comment by JoshEngebretson** [comment]
Hm, if they are in the Atomic metrics, they should be alive native side, when deleted they are cleared from the metrics via the RefCounted destructor.  This could be any number of things, happy to have a look, and I think spinning up a test case there which mimics the File use case would be ideal.  

Oh, and tracking down the resources never being released to the WeakRef's in the metrics system was "interesting", love it when a system that is supposed to help with something causes an issue with it instead, code, am I right? :)

I'll dig into the Scene/Resource conundrum with an AtomicTests today, definitely an important issue!

**Comment by mattbenic** [comment]
Indeed :)

Ok if you don't have one by tomorrow, I'll put a test case together and see if I can't make some progress on it. I'm working on a shippable C# build, so this stuff is top of my list.

**Comment by JoshEngebretson** [comment]
If you could put up a test case with File that mimics the use case, I can look into it tomorrow.

I should be able to make good progress on the Scene/Resource side of it today, at the very least will have something good to say about it.  Roger that on shipping a C# build! :shipit:

**Comment by JoshEngebretson** [comment]
Ok, I think I have good news:

PR #1478 in concert with: https://github.com/AtomicGameEngine/AtomicTests/tree/master/CSharpTests/SceneResourcesTest

Should release unused resources immediately, by unloading a scene or all scenes, and then calling ```cache.ReleaseAllResources(false);```

For example:

https://github.com/AtomicGameEngine/AtomicTests/blob/master/CSharpTests/SceneResourcesTest/Resources/Scripts/AtomicMain.cs#L43

Lemme know!

**Comment by mattbenic** [comment]
Test added for files: https://github.com/AtomicGameEngine/AtomicTests/pull/9

**Comment by JoshEngebretson** [comment]
@mattbenic Thanks, this PR should fix the File release issue, you'll need to regenerate script bindings: https://github.com/AtomicGameEngine/AtomicGameEngine/pull/1480

Lemme know on  this too! :)

**Comment by mattbenic** [comment]
Hi @JoshEngebretson. Yeah that seems to clean up the files, thanks. There's still a niggle on the scenes though, and it's related to release order. I'll PR an update to the SceneResourcesTest for it, but the gist is that if a managed reference is held to the scene when Player.UnloadScene is called, the scene contents are still not released. This is most likely to be encountered (as we do) when you have a specific scene reference and pass it to Player.UnloadScene(Scene scene), but happens with Player.UnloadAllScenes as well.

So this will work:

this.scene = null;
GetSubsystem<Player>.UnloadAllScenes();

This will not:
GetSubSystem<Player>(this.scene);
this.scene = null;

**Comment by JoshEngebretson** [comment]
That wouldn't release immediately, as would need to wait for a GC cycle.  There isn't any way to fix that, without doing am explicit GC + expiring natives.  I'll toss in a ```System.GC.Collect();``` as a test which will force a GC, and then the NativeCore should expire natives within 2 seconds.  Otherwise, that scene reference is waiting for the default GC to kick in, before being released.

This is what is called in the scene unload, which releases immediately:
https://github.com/AtomicGameEngine/AtomicGameEngine/blob/master/Script/AtomicNET/AtomicNET/Player/Player.cs#L32

BTW, the NativeCore expires natives on 2 second interval:

https://github.com/AtomicGameEngine/AtomicGameEngine/blob/master/Script/AtomicNET/AtomicNET/Core/NativeCore.cs#L165

**Comment by mattbenic** [comment]
I tested GC collects, and collect (and wait) doesn't affect it at all, including if added both after scene unload AND after ReleaseAllResources & LoadScene.

I've just tested an explicit ExpireNatives after releasing the reference to the scene though, and that does it. Would you have any objection to my exposing that in C#? (if not I'll just keep the permission change on our branch)

**Comment by JoshEngebretson** [comment]
Ok, thanks for flagging this, here is an improvement on the improved version :)

https://github.com/AtomicGameEngine/AtomicGameEngine/pull/1484

```ResourceCache.ReleaseAllResources(false);``` now does the right thing, by first forcing a ```GC.Collect()``` and expires the associated natives.  I also added a public method ```NativeCore.RunGC();``` for any situation where you want to immediately run the GC and expire natives.

**Comment by JoshEngebretson** [comment]
Ok, I believe we're good here so closin'

**Comment by mattbenic** [comment]
Agreed. I'm still struggling with texture leaks our side, which I'll ping you about later, but they're definitely not being held by the scene
